# fly.toml app configuration file generated for cats-wiki-api-stg on 2024-01-01T03:10:01Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cats-wiki-api-stg"
primary_region = "sjc"
console_command = "/rails/bin/rails console"

[build]
dockerfile = "./Dockerfile.production"

[deploy]
  release_command = "./bin/rails db:migrate"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/usr/app/public"
  url_prefix = "/"
